#ifndef LIBWYOMING_VERSION_H
#define LIBWYOMING_VERSION_H

#define LIBWYOMING_VERSION_MAJOR 0
#define LIBWYOMING_VERSION_MINOR 1
#define LIBWYOMING_VERSION_PATCH 0

#ifdef LIBWYOMING_GIT_HASH
#define LIBWYOMING_VERSION_STRING "0.1.0+" LIBWYOMING_GIT_HASH
#else
#define LIBWYOMING_VERSION_STRING "0.1.0"
#endif

#endif /* LIBWYOMING_VERSION_H */
